version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: new-pagila-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"